version: '3.9'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins-php
    ports:
      - "9080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net

  sonar:
    image: sonarqube:lts
    container_name: sonar
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
    networks:
      - jenkins_net

volumes:
  sonar_data:
  sonar_extensions:

networks:
  jenkins_net:
    driver: bridge 